# Generated by Django 5.1.6 on 2025-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ofertacarona",
            name="vagas",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="capacidade",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="marca",
        ),
        migrations.AddField(
            model_name="ofertacarona",
            name="vagas_ofertadas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ofertacarona",
            name="destino",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ofertacarona",
            name="origem",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="ano",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="cor",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="modelo",
            field=models.CharField(max_length=50),
        ),
    ]
