# Generated by Django 4.1 on 2025-02-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
