# Generated by Django 4.1 on 2025-02-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_usuario_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
